
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthProvider from './common/NextAuthProvider'
import { getServerSession } from 'next-auth'
import Navbar from './components/Navbar'
import NavarBar from './components/NavarBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session= await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          <div className="flex flex-col justify-center items-center">
            <NavarBar/>
          {children}
          </div>

        </NextAuthProvider>
        </body>

    </html>
  )
}
